### PR TITLE
Logtail more than 10 lines

### PR DESCRIPTION
**Pull request by apurvis**
Fixes https://github.com/lumoslabs/broadside/issues/28

@matl33t @albertrdixon @rfroetscher 

cc @dtboctor

### CODE REVIEW

**Comment by rfroetscher** [comment]
this makes sense to me :+1:

**Comment by apurvis** [comment]
@matl33t let me know when you release

**Comment by apurvis** [comment]
any reason we didn't push this release yet?

**Comment by matl33t** [comment]
sorry, i forgot about this. pushed to 1.2.1

**Comment by apurvis** [comment]
cool (though semantic versioning would say it should be 1.3.0 because it's a new feature... next time)

**Pull request merged**
