### PR TITLE
Move deploy, ssh, logtail, etc to their own command 

### PR DESCRIPTION
**Pull request by apurvis**
instead of being subcommands on `deploy`

also unified existence checks for all these commands that require something to actually already be deployed to run

@matl33t @rfroetscher

### CODE REVIEW

**Comment by rfroetscher** [comment]
this probably counts as breaking backward compatability

**Comment by apurvis** [comment]
yeah i think so; we could bump to 2.0.  

if we were going to do that we might also want to address the fact that `rake db:migrate` is the default predeploy command; i could do that on this branch maybe.

**Comment by rfroetscher** [comment]
there's also some stuff in the readme about being for mostly ruby and about not setting up infrastructure etc

**Comment by apurvis** [comment]
if @matl33t also thinks we should bump to 2.0 for this i'll try to tackle at least the default ruby command and the readme adjusting.

**Comment by apurvis** [comment]
on further reflection, i think if we make this change we should separate `DeployConfig` from `CommandConfig`.  i'm going to close this for now.

**Pull request closed without merging**
